language: minimal

services:
  - docker
addons:
  apt:
    update: true

before_install:
  - sudo apt-get -y install postgresql-client-11
  - docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=docker --name postgres postgres:11.5
  - sleep 10
  # Copy the database SQL file into the docker container.
  - docker cp $(pwd)/sql/create_dev_db.sql postgres:/create_dev_db.sql
  # Copy the build tables SQL file into the docker container.
  - docker cp $(pwd)/sql/build_tables.sql postgres:/build_tables.sql
  - docker exec -u postgres postgres psql -f //create_dev_db.sql
  # Run an R container with an explicit link to the Postgres container we just started
  - docker run --link postgres:postgres --rm -it --mount type=bind,source="$(pwd)",target=/app -e DB_HOST=postgres -e DB_NAME=iatlas_dev -e DB_PORT=5432 -e DB_USER=postgres -e DB_PW=docker rocker/verse R -e "source('/app/build_data_in_CI.R', chdir = TRUE)"
  - docker exec -u postgres postgres pg_dump --format custom iatlas_dev -f /tmp/iatlas_dev.pgdata
  # Copy the binary dump file to the build agent
  - docker cp postgres:/tmp/iatlas_dev.pgdata /tmp/

script: ./scripts/travis_build_db.sh
