default:
  database:
    host:     postgres
    port:     5432
    user:     postgres
    password: docker

test:
  database:
    name:     iatlas_test

dev:
  database:
    name:     iatlas_dev

prod:
  database:
    name:     xxx
    host:     xxx
    port:     5432
    user:     xxx
    password: xxx
