version: "3.8"
services:
  rstudio:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        rstudioPort: 8787
        rVersion: ${R_VERSION}
    container_name: iatlas-rstudio
    ports:
      - ${RSTUDIO_PORT}:8787
    volumes:
      - .:/home/rstudio
networks:
  default:
    external:
      name: postgres
