get_all_samples <- function() result_cached("all_samples", iatlas.data::load_all_samples())
get_datasets <- function() result_cached("datasets", iatlas.data::read_table("datasets") %>% dplyr::as_tibble() %>% dplyr::select(dataset_id = id, dataset = name))
get_features <- function() result_cached("features", iatlas.data::read_table("features") %>% dplyr::as_tibble() %>% dplyr::select(feature_id = id, feature = name))
get_genes <- function() result_cached("genes", iatlas.data::read_table("genes") %>% dplyr::as_tibble() %>% dplyr::select(gene_id = id, entrez))
get_mutation_codes <- function() result_cached("mutation_codes", iatlas.data::read_table("mutation_codes") %>% dplyr::rename(mutation_code_id = id))
get_patients <- function() result_cached("patients", iatlas.data::read_table("patients") %>% dplyr::select(patient_id = id, barcode))
get_samples <- function() result_cached("samples", iatlas.data::read_table("samples") %>% dplyr::as_tibble())
get_tags <- function() result_cached("tags", iatlas.data::read_table("tags") %>% dplyr::as_tibble() %>% dplyr::select(tag_id = id, tag = name))
get_publications <- function() result_cached("publications", iatlas.data::read_table("publications") %>% dplyr::as_tibble() %>% dplyr::select(publication_id = id, pubmed_id))
get_nodes <- function() result_cached("punodes", iatlas.data::read_table("nodes") %>% dplyr::as_tibble() %>% dplyr::select(node_id = id, name))
