get_all_samples <- function() result_cached("all_samples", load_all_samples())
get_features <- function() result_cached("features", iatlas.data::read_table("features") %>% dplyr::as_tibble() %>% dplyr::select(feature_id = id, feature = name))
get_genes <- function() result_cached("genes", iatlas.data::read_table("genes") %>% dplyr::as_tibble() %>% dplyr::select(gene_id = id, entrez, hgnc))
get_mutation_codes <- function() result_cached("mutation_codes", iatlas.data::read_table("mutation_codes") %>% dplyr::rename(mutation_code_id = id))
get_patients <- function() result_cached("patients", iatlas.data::read_table("patients") %>% dplyr::select(patient_id = id, barcode))
get_rna_seq_expr_matrix <- function() result_cached("rna_seq_expr_matrix", iatlas.data::load_rna_seq_expr(.GlobalEnv$feather_file_folder, get_genes()))
get_samples <- function() result_cached("samples", iatlas.data::read_table("samples") %>% dplyr::as_tibble())
get_tags <- function() result_cached("tags", iatlas.data::read_table("tags") %>% dplyr::as_tibble() %>% dplyr::select(tag_id = id, tag = name))
